# branches id
MAIN_OFFICE_ID = 1
MEGAMALL_ID = 2
MOA_ID = 3
FAIRVIEW_ID = 4
NORTH_EDSA_ID = 5
CLARK_ID = 6
SOUTHMALL_ID = 7
DAVAO_ID = 8
CEBU_ID = 9

newsfeeds = [
    {"text": "WELCOME TO ATTIC TOURS!", "branch": MAIN_OFFICE_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": MAIN_OFFICE_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": MAIN_OFFICE_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": MAIN_OFFICE_ID},
    {"text": "WELCOME TO ATTIC TOURS!", "branch": MEGAMALL_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": MEGAMALL_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": MEGAMALL_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": MEGAMALL_ID},
    {"text": "WELCOME TO ATTIC TOURS!", "branch": MOA_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": MOA_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": MOA_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": MOA_ID},
    {"text": "WELCOME TO ATTIC TOURS SM FAIRVIEW BRANCH!", "branch": FAIRVIEW_ID},
    {"text": "JAPAN VISA CUT-OFF TIME 1PM & 8PM", "branch": FAIRVIEW_ID},
    {"text": "JAPAN VISA PHP 1,680.00", "branch": FAIRVIEW_ID},
    {"text": "02 8829-0761 / 0916 618 6165 / attictours.fairview@gmail.com", "branch": FAIRVIEW_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": FAIRVIEW_ID},
    {"text": "#AtticToursFairview #ChoosesAtticTours #TravelJapan", "branch": FAIRVIEW_ID},
    {"text": "WELCOME TO ATTIC TOURS!", "branch": NORTH_EDSA_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": NORTH_EDSA_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": NORTH_EDSA_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": NORTH_EDSA_ID},
    {"text": "WELCOME TO ATTIC TOURS!", "branch": CLARK_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": CLARK_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": CLARK_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": CLARK_ID},
    {"text": "WELCOME TO ATTIC TOURS!", "branch": SOUTHMALL_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": SOUTHMALL_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": SOUTHMALL_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": SOUTHMALL_ID},
    {"text": "WELCOME TO ATTIC TOURS!", "branch": DAVAO_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": DAVAO_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": DAVAO_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": DAVAO_ID},
    {"text": "WELCOME TO ATTIC TOURS!", "branch": CEBU_ID},
    {"text": "PLEASE TAKE A NUMBER AND WAIT FOR YOUR NUMBER TO BE CALLED", "branch": CEBU_ID},
    {"text": "FOR PASSPORT CLAIMS, PLEASE PROCEED TO ANY WINDOW", "branch": CEBU_ID},
    {"text": "FOR INQUIRY PLEASE PROCEED TO ANY WINDOW", "branch": CEBU_ID},
]