# Generated by Django 5.0.2 on 2024-03-20 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="queue",
            table="queue",
        ),
        migrations.AlterModelTable(
            name="service",
            table="service",
        ),
    ]
