# Generated by Django 5.0.2 on 2024-04-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queues", "0002_alter_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
