# Generated by Django 5.0.2 on 2024-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queues", "0003_alter_service_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=50)),
                ("landline_no", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
