# Generated by Django 5.0.2 on 2024-02-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_rename_visa_visatype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
