# Generated by Django 5.0.2 on 2024-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_coordinator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateTimeField(verbose_name="date reported")),
            ],
        ),
    ]
