# Generated by Django 5.0.2 on 2024-02-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="coordinator",
            field=models.CharField(choices=[("A", "ARVIE")], default="", max_length=1),
        ),
        migrations.AddField(
            model_name="report",
            name="visa_type",
            field=models.CharField(
                choices=[("T", "TOURISM")], default="", max_length=1
            ),
        ),
    ]
