# Generated by Django 5.0.2 on 2024-02-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_report_coordinator_report_visa_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="coordinator",
        ),
        migrations.RemoveField(
            model_name="report",
            name="visa_type",
        ),
        migrations.AddField(
            model_name="coordinator",
            name="report",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.report",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visatype",
            name="report",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.report",
            ),
            preserve_default=False,
        ),
    ]
