# Generated by Django 5.0.2 on 2024-02-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_remove_report_coordinator_remove_report_visa_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinator",
            name="report",
        ),
        migrations.RemoveField(
            model_name="visatype",
            name="report",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
