# Generated by Django 5.0.2 on 2024-02-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="coordinator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reports.coordinator"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="visa_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reports.visatype"
            ),
        ),
    ]
