# Generated by Django 5.0.2 on 2024-02-17 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_alter_report_coordinator_alter_report_visa_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 17, 6, 11, 58, 913976, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date reported",
            ),
        ),
    ]
