# Generated by Django 5.0.2 on 2024-02-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_alter_report_report_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_date",
            field=models.DateTimeField(auto_now=True, verbose_name="date reported"),
        ),
    ]
